import Head from "next/head";
import Layout from "~/Components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout closeSidebar={true}>
        <p>This is from the home page</p>
      </Layout>
    </>
  );
}
